export { default as CustomRoute } from "./customroute"
export { default as Footer } from "./footer"
export { default as Header } from "./header"
export { default as Home } from  "./home"
export { default as Studies } from "./studies"
export { default as Offerings } from "./offerings"
export { default as About } from "./aboutus"
